# -*- coding: utf-8 -*-
"""python_13_inter-mid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CX6duLYiKxXCeLMrLPHsMUg1I-GGZTlU

분기문과 반복문
"""

#for 반복문
#i. sum = 0, 0 #초기값 설정

sum = 0
for i in range(1,11,1):  #range(start, end, interval) 1~10
    sum = sum  + i #i만큼 증가
    # print(i)
    # print(sum) #누적합


print("1에서 10까지 합은? : %d" %sum) #결과물 출력

for i in range(1,11,1):
    print(i)

for i in range(1,11,2):
    print(i)

#구구단(중첩 for 반복문)
i, k = 0, 0

for i in range(2,10,1): #앞의 숫자 범위 2~9
    for k in range(1,10,1): #곱할 숫자 범위 1~9
        print("%d * %d = %2d" %(i, k, i*k))
    print("-" * 20)

for i in range(1,10):
    print("for 반복문을 %d번 실행합니다"%i)

#break 문 (정지조건)

for i in range(1,10):
    print("for 반복문을 %d번 실행합니다"%i)
    break

#continue문 (~제외)
i, sum = 0, 0

for i in range(1,101):
    if i % 3 == 0:
        continue #3의 배수면 건너뛰기
    sum += i
    # print(i) #3의 배수 제외 숫자
    # print(sum) #누적 합

print("3의 배수 제외한 1~10까지 합계: %d" %sum) #결과값만

