# -*- coding: utf-8 -*-
"""python_01_print().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmQvRJ9aSPQ_yTFINBZ_oijgR9XbsMEs

구글콜랩 텍스트 기본 사용

**굵은 텍스트**
*이텔릭체 텍스트*
#새 섹션
##새 섹션
###새 섹션

무작정 따라하는 파이썬

* 멋진 삼행시 짓기_print()실습
* 항목 추가
"""

print("나는 데이터분석가입니다.")
print("안녕하세요...")
print("잘부탁드립니다!")

# 숫자 50과 숫자50을 더해서 출력하기

print(50 + 50)

#문자열(string) "50"과 문자열(string) "50" 더해서 출력하기

print("50" + "50")
#문자와 문자 더하면 >> 옆에 붙는다

#파이썬에서 여러 개의 원소(element, 숫자, 문자)를 담는 그릇 >> 리스트(list 목록)
print([50]+[50])

"""변수

*변하는 수
"""

apple = 1
print(apple)

Apple = "사과"
print(Apple)

#정수와 소수(부동소수점/실수)

a = 1.2
print(a)

b = 2
print(b)

print(a+b)

#문자열

가 = 'hello'
print(가)

나 = ' good morning'
#space(빈 공백)도 문자로 인식

print(가+나)

#bool

a = True
print(a)

b = False
print(b)

print(a==b)
# == : 같다

print(a != b)
#!= : 다르다

#추가

#변수에는 정수, 실수 같은 숫자를 저장할 수 있어요.

num1 = 1
num2 = 2

print(num1 - num2)

#영어나 한글과 같은 문자도 저장이 가능해요


char = "a"
print(char)

#이런 문자들의 집합도 리스트로 저장할 수 있네요.
#리스트 : 여러 원소(element)를 담는 그릇

List_ = [1,'a', 'python']
print(List_)

#그 목록(List_)에 원소 몇 개 있니?
len(List_) #len : length

"""파이썬 연산자"""

#할당 연산자
a = 1
a = a+1

print(a)

a= 1

a += 1 #a = a+1
print(a)

b = 1
b -= 2

print(b)

#산술 연산자

a = 1
b = 32

print(a>b)

c = -3 #int
d = -0.2 # float

print(c <= d)

a =1
b = 42

print(a ==b)

c = -3 #int
d = -0.2 # float

print(c != d)

#논리연산자(and, or, not)

a= True
b = False

print(a and b )
print(a or b)
print(not a)
print(not b)

#멤버(member, 소속) 연산자 (in / not in)

a = "사과"
b = ['사과', '배', '수박', '참외', ' 복숭아']

print(a in b)

c = 'apple'
d = ['Apple', 'pear', 'watermelon', 'peach']

print(c in d) #대소문자 구분

#식별연산자 (is)

a = '사과'
b = '사과'

print(a is b)

#"is"와 "=="은 다르다.
'''
==는 값이 동일한지
is는 메모리가 같은지
'''

a = [1,2,3]
b = [1,2,3]
c = a

print(a is b)

print(a is c)

print(a == b)

a = 12
b = 12  #a와 b는 메모리의 동일한 객체(정수 객체 12)를 참조해서
print(a is b )

a = "12"
b = "12"

print(a is b)

a = "사과"
b = "사과" #참조한 메모리가 달라서

print(a is b)

List_ = [1,'a', 'python']
print(List_)

print(List_)
print(List_[0])
print(List_[1])
print(List_[2])

# my_var 라는 이름의 변수를 만들고, 원하는 값을 넣어 보아요

my_var_1 = 'a' #string(문자열)
my_var_2 = List_ #리스트
print(my_var_1 + my_var_2[2])
#print(my_var_1 + my_var_2) #같은 타입끼리만 가능

#변수에 문자열로 된 정수와 실수를 저장하면

a = '345' #문자 >> 정수(int: integer)
b = '3.14' #문자 >> 실수(float)

print(a)
print(b)
print(type(a))
print(type(b))

#문자 >> 정수(int: integer)

a = int(a)
print(type(a))

#문자 >> 실수(float)
b = float(b)  #int로 바꿀시 강제로 정수로 변경해서 3으로 나옴
print(type(b))

