# -*- coding: utf-8 -*-
"""python_03_Tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gAd8-sgYVTDgDAU6x4yd6VNkvuRlLWDZ
"""



"""Tuple(튜플) 정의"""

t1 = ()
t2 = (1,2,3,4,5)
t3 = (2,4,'판다','강아지') #컬렉션 타입(여러 개의 자료형 소유가능)

t2 = (1,2,3,4,5)
print(t2[1:2])
print(t2[1])

#인덱싱(Indexing)
print(t2[0])
print(t2[-1])

#인덱싱을 통해 튜플 내부 데이터 접근 가능
#파이썬에서 index는 0부터 시작
#파이썬에서 index에 '-'기호가 붙으면, 뒤에서부터 숫자를 센다.(-1,-2,-3....)

print()
print(t3[-2])
print(t3[-3])

#슬라이싱(slicing)
#>> 튜플 안의 값의 일부만 가져오는 것
t2 = (1,2,3,4,5)
print(t2[2:])
print(t2[:4]) #n-1개까지
print(t2[1:3])
print(t2[::2]) #간격(interval)이 2칸씩 이동
print(t2[::-1]) #역순으로 -1칸씩 이동

"""튜플의 더하기. 곱하기"""

t1 = (1,2,3)
t2 = (4,5,6)
t3 = t1+t2
print(t3)

t5 =t1 * 5
print(t5)

t4 = (1,2,3,4)
#t4[-2] = 5
#tuple은 값을 임의 변경 불가
t4 = list(t4)
t4[-2] = 5
print(t4)
print()
t4 = tuple(t4)
print(t4)

"""셋(set)"""

t4 #tuple

t4 = list(t4)
#list() 사용, tuple >> list 자료형 변환
t4

t4.extend([4]) #extend(): list의 현재 list 끝에 추가
print(t4)

t4 = tuple(t4)
print(t4)

s1 = ()
#곱하기로 만든 튜플을 set에 넣어보죠.

s2 = set(t4)
print(s2) #set은 중복 제거

#s2[3]
#TypeError : 'set' object is not subscriptable
#순서가 없으니깐 indexing이 안됨

print(s2)
tto1 = tuple(s2)

print()
print(tto1[-1])

tto2 = list(s2)
print(tto2)
print()
print(tto2[-2])

"""값 추가"""

s2

#한 개의 값 추가, add()

s2.add(6)
print(s2)

#여러 개의 값 추가 undate()
print(s2)
s2.update([3,6,7,8])
print(s2)

#특정 값 제거. remove()

print(s2)
s2.remove(7)
print(s2)

"""교집합, 합집합, 차집합"""

t2 = set([1,2,3,4,5])
t3 = set([2,4,'판다','강아지'])

#교집합 intersection()

print(t2.intersection(t3))
print( t2 & t3)

#차집합 difference
print(t2.difference(t3))
print( t2 - t3)

#합집합 union
print(t2.union(t3))
print( t2 | t3)

