# -*- coding: utf-8 -*-
"""python_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIcIDJ5gOCZRLVp2V6uP9gMeh57Vi_kr
"""



"""비교 연산자 활용하기"""

print(3==3)

ans1 = 3 ==3
print(ans1)

print(5<3)

(3==3) and (2<4) and (3<5)

(4>6) or ('apple' == 'Apple') or (1 != 0) #False or False or True

(4>6) or ('apple' == 'Apple') or (1 != 1) # False or False or False

not (False)

#비교연산자 적용, 반복문 만들기

num = int(input()) # input()으로 사용자가 입력값을 받은 값 >> 문자(string)
#int()정수를 만들어주는 함수(integer 함수)사용, 문자 >> 숫자 변경('22' >> 22)

if num % 2 == 0:  # % 나머지
    print(num, "짝수입니다")
else:
    print(num, "홀수입니다")

#변수 ans에 숫자 1~50 중 하나를 넣어 볼거예요

ans = 25

submit = int(input())

if ans < submit:
    print("정답보다 더 큰 수를 입력했네요, 다시 입력하세요")
elif ans == submit:
    print("와우, 정답")
else:
    print("정답보다 더 적은 수를 입력하셨네요. 다시 입력하세요")

