# -*- coding: utf-8 -*-
"""python_17_try_except.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11kJr_DfW1tRLcP2U1hd8AMQtyoEeQKzi

예외처리
"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd

#try - except

import os

try:
    os.remove('./text.txt')
except:
    print("그런 파일 없습니다")

mycampus ='나는 현재 대한민국 최고의 IT 데이터분석 & 개발자 양성소인 멀티 캠퍼스 교육생이다.\
억대 연봉자.데이터사이어티스가 되겠다는 나의 꿈을 바로 이 곳, 멀티 캠퍼스에서 이룰 것이다.'

posList = [ ]
position = 0

while True:
    try:
        multi = mycampus.index('멀티',position)
        posList.append(multi)
        position += 1
    except:
        break

print("멀티 글자 위치: ", sorted(list(set(posList))))

mycampus.index("멀티")

#예외처리

n1 = input("숫자1 : ")
n2 = input("숫자2 : ")

try:
    n1 = int(n1)
    n2 = int(n2)

    while True:
        res = (n1/n2)


except ValueError:
    print("문자열을 입력하셨어요. 숫자로 입력 부탁드려요")
except ZeroDivisionError:
    print("0으로 나눌 수가 없어요. 다른 숫자 입력 부탁드려요")
except KeyboardInterrupt:
    print("강제종료 KEY를 누르셨네요")

