# -*- coding: utf-8 -*-
"""python_11_chatgpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SasBaNULm3wqP6cjltGjC8UjBaXPRvqJ
"""

#print()는 실행할 때, 내가 볼 수 있도록 실행화면에 "출력"하는 명령어
#괄호()안에 값을 넣어줌

print('hello')

"""변수"""

#변수에 값 할당하기
age = 25
name = 'John'
is_student = True

#변수 값 출력하기
print("나이:", age)
print("이름:", name)
print("학생여부:", is_student)

print('hello 이예진')
myname = "카리나"
print("hello " +myname + "!")

name = "emma"
greeting = "안녕"
print("이름 : ", name)
print("인사 : ", greeting)

#우리가 사용하는 두 개 이상의 문자가 모이면 >> 문자열
#문자열은 따옴표 안에 문자를 집어 넣음

myname = "이예진"

"""숫자"""

#정수
a = 10
b = -5
result = a + b
print("덧셈결과:", result)

#실수float

pi = 3.14
radius = 2.5
area = pi*(radius **2)
print("원의 넓이: ", area)

#숫자는 소수점이 없는 것(정수)와 있는 것(소수)로 나뉨
num1 = 10
num2 = 1.2
myname = "이예진"
print(type(num1))
print(type(num2))
print(type(myname))

#참/거짓 - 따옴표 없이 첫 글자를 대문자로 사용!

is_adult = True
is_woman = False

is_student = True
is_adult = False

print("학생 여부:", is_student)
print("성인 여부:", is_adult)

"""리스트(list)
- 리스트는 목록
-리스트 안에는 아무거나 들어갈수 있음(숫자, 문자 상관없다)

"""

fruits = ['apple','bear','orange']
print(fruits[0])

fruits.append('mongo')
print(fruits)

#리스트 생성하기
num = [1,2,3,4,5]
fruits = ['apple','bear','orange']
mixed_list = [10,"hello", True, 3.14]

#리스트 요소에 접근하기
print("첫 번째 과일:", fruits[0]) #apple
print("두 번째 숫자:", num[1]) #2

#리스트 요소 수정하기
fruits[0] = "cherry"
print("수정된 첫 번째 과일:", fruits[0]) #cherry

# 리스트에 요소 추가하기
fruits.append("grape")
print("추가된 과일:", fruits)

# 리스트에서 요소 제거하기
fruits.remove("bear")
print("제거된 과일:", fruits)

"""딕셔너리(dictionary)"""

a_dict = {} #빈 딕셔너리 생성
print(a_dict)

a_dict = {'name': '이예진','age':25}
print(a_dict)

print(a_dict['name'])

# 사전 생성하기
student = {
      "name":"emma",
      "age": 25,
      "sex": "female"
}

#key를 사용하여 값에 접근하기
print("name: ", student["name"])
print("age: ", student["age"])

#사전 값 수정하기
student["age"] = 26
print("new age: ", student["age"])

#새로운 키-값 쌍 추가하기
student["school"] = "korea univercity"
print("school: ", student["school"])

# 키를 사용하여 사전에서 항목 제거하기
del student["sex"]
print("remove sex: ", student)

"""문자열 응용"""

#문자열 간의 더하기는 두 문자열을 이어붙인 문자열

name1 = "lee"
name2 = "yejin"

print(name1 + " " + name2)

'''
a = "3"
b = 5

print(a+b)
TypeError: can only concatenate str (not "int") to str

문자열과 숫자형은 더할 수 없다
'''

# 위 문제를 해결하기 위해서 숫자 간 더하는 것으로 바꾸자 (문자 >> 숫자)

a = "3"
b = 5

a = int(a)

print(a+b)

# 그럼 문자열에 숫자를 담은 것은 언제 쓰지?
# 문자와 숫자를 조합하는 경우에 사용

myteam = "drwill"
myid = "55"

mynumber = myteam + myid

print(mynumber)

"""특정 문자를 기준으로 문자열 나누기"""

#이메일 주소에서 도메인 'gmail' 만 추출하기

myemail = 'test@gmail.com'

print(myemail)
print(myemail.split('@'))

result = myemail.split('@')
print('--------------------------')

print(result[0])
print(result[1])

result2 = result[1].split('.')
print(result2)

print(result2[0]) #gmail
print(result2[1]) #com

#한 줄로 한번에 처리 (method chaining 메서드 체인)
myemail.split('@')[1].split('.')[0]

"""특정 문자를 다른 문자로 바꾸기"""

txt = '서울시-마포구-망원동'
print(txt.replace("-", ">"))

mail = 'yahoo.co.kr'

mail.replace("yahoo.","")

"""질의응답"""

'''
이메일이나 주소를 사용하다 보면 옛날에 co.kr 이런거 쓰던경우가 있었는데
이때 .을 기준으로 분리하면 co 와 kr 도 분리되어 버리는데 이부분은 분리 안되게 할려면 어떻게 해야하나요?
'''

mail = 'yahoo.co.kr'
a = mail.split(".")
print(a)

b = '.'.join([a[1],a[2]])
print(b)

mail.split('.',maxsplit = 1)

"""join()함수"""

과일 = ['사과','배','딸기']

'-'.join(과일)

import re

homepage = 'dldpwls716.co.kr'
parts = re.split(r'\.', homepage[-5:])

result = ".".join(parts)
print(result)

re.split(r'\.', homepage)