# -*- coding: utf-8 -*-
"""python_15_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ih4PhIcmlJfPOSrEdxyYL3n5jr8CwOtc

문자열 기본
"""

a = [1,2,3,4,5]

print(a[0])
print(a[1:3])

s = "멀티캠퍼스_데이터분석 및 개발자과정_8기"

#count() : 찾을 문자열이 몇 개 있는 지 , 개수를 세는 함수

s.count("-")

#find()함수
#찾는 문자열이 없으면 -1

s.find("분석")

#index(): find()랑 유사하다 단, 없으면 에러 발생

#join()

a = ','
a.join(['my','name','is'])

a = '/'
a.join(['my','name','is'])

"""문자열 중요 내장 함수"""

#upper/ lower

#upper : 전부 대문자로 변환
#lower : 전부 소문자로 변환

#replace()
a = 'Multicampus'

a.replace('c','C')

b = 'd  e  r'
c =  b.replace(' ',"")
print(b)

ai = '나는 인공지능 데이터 분석가 및 개발자다'

print(ai)
print(ai.split(' '))

f = "           이예진      "

print(f.lstrip()) #왼쪽공백을 없앰
print(f.rstrip()) #오른쪽공백을 없앰
print(f.strip())  #양쪽 공백을 없앰

a.swapcase()

"""문자열 분리 및 결합

* split(), join(),splitlines()
"""

s = "닥터윌과 함께 파이썬을 열공하는 중... 한숨이 나옴"

s.split()

a = '5시:40분: 끝내줄까?'
a.split(':')

b = '제발요\n안그러면\n수업거부할꺼예요'
print(b)
b.split('\n')

b.splitlines()

c = "/"
c.join('이예진')

#문자열

s = input('날짜(연/월/일) 입력하세요: ')
print(s)

s.split('.')

split_s = s.split('.')

print(split_s[0])

print("입력한 날짜의 10년 후: ", end="")
print(str(int(split_s[0])+10) + "년", end="")

s='Multicampus'
s.isdigit()

