# -*- coding: utf-8 -*-
"""python_14_list_dict_while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/186A-QvT7s3_yzKk4virYKLVRFPEgVYeF

1.리스트(list)
"""

a, b, c, d = 10,20,30,40

print(a)
print(b)

aa = [10,20,30,40]

print(aa[0])
print("------")
print(aa[-1])

#list 와 range활용

list(range(10))

a = list(range(10))
print(a)
print(type(a))

#역순출력
list(range(10,0,-1))

#홀수 출력
list(range(1,10,2))

#문자 출력
list("이예진")

#for문과 함께 사용
a = [10,20,30,40]

for i in a:
    print(i)

#enumerate(**) : index와 요소(element)를 함께 출력
a = [10,20,30,40]

for i, j in enumerate(a):
    print(i,j)

a = [10,20,30,40]

for i, j in enumerate(a,start=1):
    print(i,j)

#리스트 합 구하기
a = [10,20,30,40]

sum = 0
for i in range(4):
      sum += a[i]
      # print(sum)
      # print(sum)


print(sum)

a = [10,20,30,40]

sum = 0
for i in range(4):
    sum += a[i]

print(sum)

#[실전]리스트 합 구하기
aa = []

#리스트 초기화

for i in range(0,4):
      aa.append(0)
sum = 0


#리스트에서 자료 입력받기

for i in range(0,4):
      aa[i] = int(input(str(i+1)+ "번째 숫자: "))

#리스트 합 구하기
for i in range(0,4):
    sum += aa[i]

#리스트 값 구하기
print("총합: %d" %sum)

aa = []
sum = 0

for i in range(4):
    aa.append(0)

for i in range(4):
    aa[i] = int(input(str(i+1) + "번째 숫자: "))

for i in range(4):
    sum += aa[i]

print("총합 : %d" %sum)

a = [10,20,30,40,50,60,70,80,90]
a[:len(a)]

a[:len(a)-1]

a[1] = [300,301]
print(a)

a[1]
a[1][0]

del a[:2]
print(a)

b = [40,50,60]
a+b

"""2. 리스트 조작함수"""

# 1) count(값)

c = [40,50,60,60,70,70,70,80,90]

print(c.count(70))
print(c.count(60))

# 2) reverse() : 리스트에서 요소의 순서를 역순

print(c)
c.reverse()
print(c)

list(reversed(c)) #일회성

#sort() 리스트 요소를 오름차순으로 정렬
c = [40,50,60,60,70,70,70,80,90]

print(c)
c.sort()

c.sort(reverse=True) #내림차순
print(c)

e = [40,50,60,70,80,90]
sorted(e)
print(e)

sorted(e, reverse = True)
# print(e)

e.sort()
print(e)

"""리스트 복사
-얕은복사(shallow copy/ soft copy)
-깊은 복사 (deep copy)
"""

#얕은복사
a = [1,2,3,4]
b = a

print(a,b)

#리스트 요소 값 변경
b[2] = 100
b

print(a,b)

#깊은 복사(deep copy)

b= a.copy()

a == b

a is b  #b는 a의 복사본이라서
print(a,b)

#b값만 변경 원본 a는 그대로
b[2] = 3
print(a,b)

"""append와 extend

*append(): 리스트 맨 뒤에 요소 추가
*extend(): 리스트 결합
"""

print(a)

print(a.append(30))
print(a)

print(a,b)

print(a.extend(b))

print(a,b)

a.extend(b)

print(a)

a =[1, 2, 100, 4, 30, 1, 2, 3, 4]
print(a)

print(set(a))

set_a = set(a)
list(set_a)

"""insert()

*리스트 특정 index요소추가
"""

f = [10,20,30]

f.insert(2, 500)

print(f)

f.insert(len(f), 200)
print(f)

"""pop()

*해당 index 요소를 삭제 (맨뒤에 날리기)

"""

g = [10,20,30]

g.pop()
print(g)

"""del vs remove

*del 은 delete 약자. 특정 인덱스 값 삭제
*remove는 list에서 특정 '값'찾아서 삭제
"""

#del
print(g)

del g[1]
print(g)

#remove

h = [1,2,3]
h.remove(2)
print(h)

"""clear()

*요소를 완전 제거
"""

a = [10,20,30]
a.clear()
print(a)

a = [10,20,30]
a = []
print(a)

"""[실습] 연유라떼 얼마?

"""

menu = ['아메리카노','밀크티','연유라떼','카푸치노','카페라떼']
price = [2500,4500,4000,3500,4000]

연유라떼 = price[2]
print('{}원입니다'.format(연유라떼))

menu = {'아메리카노' : 2500,
        '밀크티' : 4500,
        '연유라떼' : 4000,
        '카푸치노' : 3500,
        '카페라떼' : 4000
        }

coffee = dict(zip(menu, price))
coffee['연유라떼']

연유라떼 = dict(zip(menu, price))['연유라떼']
print('{}원 입니다.'.format(연유라떼))

#카페라떼는 얼마인가요?
menu = ['아메리카노','밀크티','연유라떼','카푸치노','카페라떼']
price = [2500,4500,4000,3500,4000]

#1.
# 카페라떼 = dict(zip(menu, price))['카페라떼']
# print('{}원 입니다.'.format(카페라떼))

#2.
# coffee = dict(zip(menu, price))
# coffee['카페라떼']

#index()

menu.index('카페라떼')

print(price)
print(price[menu.index('카페라떼')]) #price[4]

"""리스트 컴프리헨션(list comprehension)"""

list(range(10))

[i for i in list(range(10))]

[i+5 for i in list(range(10))]

[i*2 for i in list(range(10))]

#리스트 컴프리헨션과 if 조건문 같이 사용

[i for i in list(range(10)) if i % 2 == 0]

#리스트 안에 있는 실수를 정수로 바꿔서 실행
a = [1.2,3.4,5.6,7.8]
for i in range(len(a)):
    a[i] = int(a[i])
print(a)

# map() (**) map(바꿀자료형태, 바꿀변수)
a = [1.2,3.4,5.6,7.8]

list(map(int, a))

#튜플(상수)

t1 = (10,20,30)

t1, type(t1)

t2 = 10,20,30 ; t2

#dict()
# key:value

stu = {'id' : 7, 'name' : "son", 'dept' : 'kfa' }
print(stu)

print(stu.keys())

print(stu.values())

list(stu.values())

stu['tel'] = '010-1234-5667'
stu

list(stu.items())

for i, j in stu.items():
    print(i,j)

stu['adr'] = 'tottenham'
stu

stu

if 'email' not in stu:
    stu['email'] = stu['name'] + '@mulcam.com'

stu

#성별

stu['gender'] = input("성별을 입력하시오: ")

stu

#실습
#번호, 이름, 별명,주 스킬, 주소, 이메일주소, 성별, 연락처(010-1234-5678)

profil = {}


profil['번호'] = int(input("번호를 입력하세요 : "))
profil['이름'] = input("이름을 입력하세요 : ")
profil['별명'] = input("별명을 입력하세요 : ")
profil['주 스킬'] = input("주 스킬을 입력하세요 : ")
profil['주소'] = input("주소를 입력하세요 : ")
profil['이메일 주소'] = input("이메일 주소를 입력하세요 : ")
profil['성별'] = input("성별을 입력하세요 : ")
profil['연락처'] = input("연락처를 입력하세요 : ")


print()
print(profil)

# for i,j  in a.items():

#     print(f"{i} : {j}")

profil = {'번호': 4,
          '이름': '이예진',
          '별명': '예방이',
          '주 스킬': '바리스타',
          '주소': '부산',
          '이메일 주소': 'dldpwls716@naver.com',
          '성별': '여자',
          '연락처': '010-1234-5678'}

print(profil)

# profil = {


#         "번호" : int(input("번호를 입력하세요 : "))
#         "이름" : input("이름을 입력하세요 : ")
#         '별명' == input("별명을 입력하세요 : ")
#         '주 스킬' == input("주 스킬을 입력하세요 : ")
#         '주소' == input("주소를 입력하세요 : ")
#         '이메일 주소' == input("이메일 주소를 입력하세요 : ")
#         '성별' == input("성별을 입력하세요 : ")
#         '연락처' == input("연락처를 입력하세요 : ")
#         }

#for문 활용
blackpink = {}

blackpink["이름"] = "blackpink"
blackpink["멤버수"] = "4명"
blackpink["대표곡"] = "뚜두뚜두"

for i in blackpink.keys():
    print(f'{i} >>  {blackpink[i]}')

print(blackpink.keys())

#while문 활용 menu 주문 프로그램만들기
#1유형

menu = {
    '떡볶이' : '순대',
    '짜장면' : '짬뽕',
    '라면' : '김치',
    '피자' : '피클',
    '맥주' : '땅콩',
    '치킨' : '치킨무',
    '삼겹살' : '파채',
}

while 1:
  a = input("좋아하는 음식은? '떡볶이', '짜장면','라면','피자','맥주','치킨','삼겹살'")

  if a in menu:
      print(f'궁합음식: {a} ---> {menu[a]}')
  elif a == 'q':
      break
  else:
      print('그런 음식은 여기에 없습니다. 다시 입력하세요')

#2유형

menu = {
    '떡볶이' : '순대',
    '짜장면' : '짬뽕',
    '라면' : '김치',
    '피자' : '피클',
    '맥주' : '땅콩',
    '치킨' : '치킨무',
    '삼겹살' : '파채',
}

while True:
    name = list(menu.keys())
    a = input("좋아하는 음식은?" + str(name))
    if a in name:
        print(menu[a])
    else:
        print('그런 음식은 여기에 없습니다. 다시 입력하세요')
        break

#3유형
menu = {
    '떡볶이' : '순대',
    '짜장면' : '짬뽕',
    '라면' : '김치',
    '피자' : '코카콜라',
    '맥주' : '땅콩',
    '치킨' : '소떡소떡',
    '삼겹살' : '소주',
}

while True:
    want = input("저녁메뉴 고르시오: " + str(list(menu.keys())))
    if want in menu:
        print("궁합에 맞는 음식은 %s ------> %s "%(want,menu.get(want)))
    elif want == "없음":
        break
    else:
        print("메뉴를 다시 고르세요")

#실습

place = {
    '부산' : '해운대',
    '울산' : '태화강',
    '광주' : '펭귀마을',
    '서울' : '남산타워',
    '인천' : '영종도',
    '강원도' :'설악산',
    '춘천' : '남이섬',
    '남해' : '다랑이마을',
    '하동' : '녹차밭',
    '대구' : '동성로',
}

while True:
    a = input("가고싶은 지역을 입력하세요!: \n" + str(list(place.keys())))

    if a in place:
        print("%s에 가시면 %s 장소를 추천드려요 "%(a,place.get(a)))
    elif a == "없음":
        break
    else:
        print("입력하신 지역이 없습니다. 다시 입력해주세요~~")