# -*- coding: utf-8 -*-
"""python_12_chatgpt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uEScH5HJiQhB0HHdyfi6xQC27wQyTKH

조건문
"""

#if

'''
if 조건:
    조건이 true일때 실행 할 코드

'''

age =21

if age > 19:
    print("성인입니다")

#elif

'''
elif 문은 else if
여러 개 조건 중 하나가 True인 경우
if 나 elif 중 하나만 실행

if 조건 1:
    조건 1이 True일때 실행할 코드

elif 조건 2:
    조건1이 참이 아니고 조건 2가 True일때 실행할 코드
    '''

score = 85

if score >=90:
    print("A")
elif score >=80:
    print("B")
else:
    print("등급 줄 수 없음(미달)")

#else 문

'''
else문은 이전의 모든 조건이 False일때 실행
if 나 elif 중 어느것도 참이 아닐때

if 조건:
    조건이 True일 때 실행되는 코드

else:
    위의 모든 조건이 False일 때 실행하는 코드

'''

age =15

if age >=19:
    print("성인")
else:
    print("미성년자")

"""반복문"""

#for 반복문
'''
for 반복문은 시퀀스(리스트,튜플,문자열) 항목들을 순화하거나,
특정 횟수 동안 반복 작업 수행할 때 사용된다.

for 변수 in 리스트(튜플, 문자열):
    수행할 문장1
    수행할 문장2
'''

fruits = ['apple','bear','orange','persimmon']

for fruit in fruits:
    print(fruit)

fruits = ['apple','bear','orange','persimmon']
for fruit in fruits:
    print(fruit)

mes = "안녕하세요"
for char in mes:
    print(char)

"""while 반복문"""

#while loop

'''
while반복문은 주어진 조건이 True인 경우 코드 블록을 계속 실행함
조건이 False가 되면 반복이 종료됨

while 조건문:
    수행할 문자1
    수행할 문자2
    수행할 문자3
'''

count = 1

while count < 6:
    print(count)
    count = count +1

"""반복문 + 조건문"""

# 1부터 100까지 숫자 중에서 3의 배수인 숫자를 출력

num = 1

while num <= 100:
    if num % 3 ==0:
      print(num)
    num += 1

#사용자로부터 입력 받아 처리하기
total = 0

while True:
    num = int(input("숫자를 입력하세요 (0을 입력하면 종료)"))
    if num == 0:
        break
    total += num
print("총합", total)

"""커피 자판기 만들기



"""

choice = input("커피 자판기를 사용하시겠습니까? (yes/ no)입력 \n")

if choice == 'yes':
    while True:
        money = int(input("돈을 넣어주세요(예시: 1000, 10000)\n"))
        num = int(input("숫자를 선택하세요. 1. 아이스 아메리카노 , 2.카페 라떼, 3. 콜드브루\n"))

        if num == 1:
            print("아이스 아메리카노를 선택하셨습니다. 거스름돈은 ", money-1000, "원 입니다.")
            # break

        elif num == 2:
            print("카페 라떼를 선택하셨습니다. 거스름돈은 ", money-1500, "원 입니다.")
            # break

        elif num == 3:
            print("콜드브루를 선택하셨습니다. 거스름돈은 ", money-2000, "원 입니다.")
            # break

        else:
            print("없는 메뉴입니다.")
        break

#커피 자판기
coffee_menu = {
    "에스프레소": 3000,
    "아메리카노": 3500,
    "카페라떼": 4000,
    "카푸치노": 4500
}

orders = []

print("커피 자판기를 시작합니다. 주문을 완료하려면 '종료'를 입력하세요")

while True:
    coffee_name = input("주문할 커피 종류를 입력하세요 : ")
    if coffee_name == "종료":
        break
    quantity = int(input("주문 수량을 입력하세요 : "))

    if coffee_name in coffee_menu:
        order_price = coffee_menu[coffee_name] * quantity
        orders.append((coffee_name, quantity, order_price))
        print(f'{coffee_name} {quantity}잔이 주문되었습니다.')
        break
    else:
        print("커피 메뉴에 없는 항목입니다. 다시 주문해주세요")

print("\n주문 내역 ")

totla_price = 0
for order in orders:
    coffee_name, quantity, order_price = order
    print(f'{coffee_name}: {quantity}잔, 가격: {order_price}원')
    totla_price += order_price

print(f"\n총 주문 금액: {totla_price}원")
print("이용해 주셔서 감사합니다. 안녕히 가십시오!")

coffee_menu[coffee_name]

"""함수"""

'''
def make_apple_juice(apple):"
  return "사과주스
'''

def make_apple_juice(apple):
    return "사과주스"

# x : 매개변수

make_apple_juice("사과")

# 두 수를 더하는 함수 정의
def add_numbers(x, y):
    sum = x + y
    return sum
# 함수 호출
result = add_numbers(5, 3)
print("결과:", result)  # 출력: 8

# 문자열에서 부분 문자열 대체하기
original_string = "안녕하세요! 오늘은 파이썬을 공부합니다."
new_string = original_string.replace("안녕하세요", "Hello")
print("새로운 문자열:", new_string)
# 출력: 새로운 문자열: Hello! 오늘은 파이썬을 공부합니다.
# 대소문자 구분하는 경우
original_string = "Hello world! Hello Python!"
new_string = original_string.replace("hello", "hi")
print("새로운 문자열:", new_string)
# 출력: 새로운 문자열: Hello world! Hello Python!